development: &default
  adapter:   postgresql
  encoding:  utf8
  username:
  password:
  pool:      2
  timeout:   5000
  database:  ashby-village_development

test:
  <<: *default
  database: ashby-village_test
